"""Alpha diversity visualization tools for X-Amplicon outputs."""

from __future__ import annotations

try:
    import matplotlib
except ModuleNotFoundError:
    matplotlib = None
else:
    matplotlib.use("Agg")

import os
from typing import Any, Sequence

import pandas as pd
import plotly.express as px

from .viz_common import (
    DEFAULT_ALPHA_BARPLOT_DIR,
    DEFAULT_ALPHA_BOXPLOT_DIR,
    DEFAULT_ALPHA_RAREFACTION_DIR,
    DEFAULT_ALPHA_METRICS,
    apply_publication_theme,
    build_sample_metadata,
    ensure_output_dir,
    normalize_alpha_table,
    read_table,
    resolve_color_palette,
    resolve_alpha_metrics,
    sort_groups,
    validate_output_format,
    write_chart_index,
    write_html_dashboard,
    write_html_figure,
    write_optional_static,
    write_table,
)


def _merge_alpha_metadata(
    alpha_path: str,
    metadata_path: str | None,
    sample_id_col: str,
    group_col: str,
) -> pd.DataFrame:
    alpha = normalize_alpha_table(alpha_path)
    sample_meta = build_sample_metadata(
        alpha["SampleID"].tolist(),
        metadata_path=metadata_path,
        sample_id_col=sample_id_col,
        group_col=group_col,
    )
    merged = alpha.merge(sample_meta, on="SampleID", how="left", validate="one_to_one")
    return merged.loc[:, ["SampleID", "Group", *DEFAULT_ALPHA_METRICS]].copy()


def _alpha_long_table(merged: pd.DataFrame, metrics: Sequence[str]) -> pd.DataFrame:
    return merged.melt(
        id_vars=["SampleID", "Group"],
        value_vars=list(metrics),
        var_name="Metric",
        value_name="Value",
    )


def plot_alpha_boxplots(
    alpha_diversity_path: str = "work/06_final/alpha/alpha_diversity.tsv",
    metadata_path: str | None = "work/00_input/metadata.txt",
    output_dir: str = DEFAULT_ALPHA_BOXPLOT_DIR,
    metrics: list[str] | None = None,
    sample_id_col: str = "SampleID",
    group_col: str = "Group",
    output_format: str = "html",
    color_palette: str | list[str] | dict[str, str] | None = None,
) -> dict[str, Any]:
    """Generate alpha diversity boxplots grouped by metadata.

    Args:
        alpha_diversity_path: Alpha diversity TSV generated by the pipeline.
        metadata_path: Metadata TSV containing sample and group columns. If it
            is missing, groups are inferred from sample IDs.
        output_dir: Directory for generated plots and tables.
        metrics: Alpha metrics to plot. Defaults to all supported metrics.
        sample_id_col: Metadata column containing sample IDs.
        group_col: Metadata column containing group labels.
        output_format: `html`, `png`, `pdf`, `svg`, or `all`. Static formats require
            kaleido; HTML is always attempted.
        color_palette: Optional comma-separated colors or `Group:#hex` pairs.

    Returns:
        A dictionary describing generated files and skipped static exports.

    Raises:
        FileNotFoundError: If required input files are missing.
        ValueError: If required columns or metric values are invalid.
    """

    output_format = validate_output_format(output_format)
    resolved_output_dir = ensure_output_dir(output_dir)
    resolved_metrics = resolve_alpha_metrics(metrics)
    merged = _merge_alpha_metadata(
        alpha_diversity_path,
        metadata_path,
        sample_id_col=sample_id_col,
        group_col=group_col,
    )
    long_table = _alpha_long_table(merged, resolved_metrics)
    long_path = write_table(
        long_table,
        os.path.join(resolved_output_dir, "alpha_boxplot_long.tsv"),
        include_index=False,
    )

    figures: dict[str, Any] = {}
    generated_files = [long_path]
    skipped_static: list[str] = []
    group_order = sort_groups(merged["Group"].astype(str).tolist())
    color_map = resolve_color_palette(group_order, color_palette=color_palette)

    for metric in resolved_metrics:
        metric_table = long_table.loc[long_table["Metric"] == metric].copy()
        fig = px.box(
            metric_table,
            x="Group",
            y="Value",
            color="Group",
            points="all",
            hover_data=["SampleID"],
            category_orders={"Group": group_order},
            color_discrete_map=color_map,
            title=f"{metric} Alpha Diversity",
            labels={"Value": metric},
            width=900,
            height=620,
        )
        fig.update_layout(showlegend=False, title_x=0.5)
        apply_publication_theme(fig, width=900, height=620)
        figures[metric] = fig

        if output_format in {"html", "all"}:
            generated_files.append(
                write_html_figure(
                    fig,
                    os.path.join(resolved_output_dir, f"alpha_boxplot_{metric.lower()}.html"),
                )
            )
        write_optional_static(
            fig,
            os.path.join(resolved_output_dir, f"alpha_boxplot_{metric.lower()}"),
            output_format,
            width=900,
            height=620,
            generated_files=generated_files,
            skipped_static=skipped_static,
        )

    if output_format in {"html", "all"}:
        generated_files.append(
            write_html_dashboard(
                figures,
                os.path.join(resolved_output_dir, "alpha_boxplots.html"),
                "Alpha Diversity Boxplots",
            )
        )
    generated_files.append(
        write_chart_index(
            resolved_output_dir,
            "Alpha Diversity Boxplots",
            generated_files,
            "Per-metric alpha diversity boxplots grouped by sample metadata.",
        )
    )

    return {
        "alpha_diversity": os.path.abspath(alpha_diversity_path),
        "metadata": None if metadata_path is None else os.path.abspath(metadata_path),
        "output_dir": resolved_output_dir,
        "metrics": resolved_metrics,
        "long_table": long_path,
        "plots": generated_files,
        "skipped_static_exports": skipped_static,
    }


def plot_alpha_barplots(
    alpha_diversity_path: str = "work/06_final/alpha/alpha_diversity.tsv",
    metadata_path: str | None = "work/00_input/metadata.txt",
    output_dir: str = DEFAULT_ALPHA_BARPLOT_DIR,
    metrics: list[str] | None = None,
    sample_id_col: str = "SampleID",
    group_col: str = "Group",
    output_format: str = "html",
    color_palette: str | list[str] | dict[str, str] | None = None,
) -> dict[str, Any]:
    """Generate group mean alpha diversity barplots with standard deviation.

    Args:
        alpha_diversity_path: Alpha diversity TSV generated by the pipeline.
        metadata_path: Metadata TSV containing sample and group columns. If it
            is missing, groups are inferred from sample IDs.
        output_dir: Directory for generated plots and summary tables.
        metrics: Alpha metrics to plot. Defaults to all supported metrics.
        sample_id_col: Metadata column containing sample IDs.
        group_col: Metadata column containing group labels.
        output_format: `html`, `png`, `pdf`, `svg`, or `all`. Static formats require
            kaleido; HTML is always attempted.
        color_palette: Optional comma-separated colors or `Group:#hex` pairs.

    Returns:
        A dictionary describing generated files and skipped static exports.

    Raises:
        FileNotFoundError: If required input files are missing.
        ValueError: If required columns or metric values are invalid.
    """

    output_format = validate_output_format(output_format)
    resolved_output_dir = ensure_output_dir(output_dir)
    resolved_metrics = resolve_alpha_metrics(metrics)
    merged = _merge_alpha_metadata(
        alpha_diversity_path,
        metadata_path,
        sample_id_col=sample_id_col,
        group_col=group_col,
    )
    group_order = sort_groups(merged["Group"].astype(str).tolist())
    color_map = resolve_color_palette(group_order, color_palette=color_palette)
    summary = (
        merged.groupby("Group", sort=False)[resolved_metrics]
        .agg(["mean", "std"])
        .fillna(0.0)
    )
    summary.columns = [f"{metric}_{stat}" for metric, stat in summary.columns.to_flat_index()]
    summary = summary.reset_index()

    summary_rows: list[pd.DataFrame] = []
    for metric in resolved_metrics:
        metric_summary = summary.loc[:, ["Group", f"{metric}_mean", f"{metric}_std"]].copy()
        metric_summary = metric_summary.rename(
            columns={f"{metric}_mean": "Mean", f"{metric}_std": "Std"}
        )
        metric_summary.insert(1, "Metric", metric)
        summary_rows.append(metric_summary)
    summary_long = pd.concat(summary_rows, ignore_index=True)
    summary_path = write_table(
        summary_long,
        os.path.join(resolved_output_dir, "alpha_group_summary.tsv"),
        include_index=False,
    )

    figures: dict[str, Any] = {}
    generated_files = [summary_path]
    skipped_static: list[str] = []
    for metric in resolved_metrics:
        metric_table = summary_long.loc[summary_long["Metric"] == metric].copy()
        fig = px.bar(
            metric_table,
            x="Group",
            y="Mean",
            color="Group",
            error_y="Std",
            category_orders={"Group": group_order},
            color_discrete_map=color_map,
            title=f"{metric} Group Mean",
            labels={"Mean": metric},
            width=900,
            height=620,
        )
        fig.update_layout(showlegend=False, title_x=0.5)
        apply_publication_theme(fig, width=900, height=620)
        figures[metric] = fig

        if output_format in {"html", "all"}:
            generated_files.append(
                write_html_figure(
                    fig,
                    os.path.join(resolved_output_dir, f"alpha_barplot_{metric.lower()}.html"),
                )
            )
        write_optional_static(
            fig,
            os.path.join(resolved_output_dir, f"alpha_barplot_{metric.lower()}"),
            output_format,
            width=900,
            height=620,
            generated_files=generated_files,
            skipped_static=skipped_static,
        )

    if output_format in {"html", "all"}:
        generated_files.append(
            write_html_dashboard(
                figures,
                os.path.join(resolved_output_dir, "alpha_barplots.html"),
                "Alpha Diversity Group Mean Barplots",
            )
        )
    generated_files.append(
        write_chart_index(
            resolved_output_dir,
            "Alpha Diversity Group Mean Barplots",
            generated_files,
            "Group-level alpha diversity mean and standard deviation barplots.",
        )
    )

    return {
        "alpha_diversity": os.path.abspath(alpha_diversity_path),
        "metadata": None if metadata_path is None else os.path.abspath(metadata_path),
        "output_dir": resolved_output_dir,
        "metrics": resolved_metrics,
        "summary_table": summary_path,
        "plots": generated_files,
        "skipped_static_exports": skipped_static,
    }


def plot_alpha_rarefaction_curve(
    alpha_rarefaction_path: str = "work/06_final/alpha/alpha_rarefaction.tsv",
    metadata_path: str | None = "work/00_input/metadata.txt",
    output_dir: str = DEFAULT_ALPHA_RAREFACTION_DIR,
    sample_id_col: str = "SampleID",
    group_col: str = "Group",
    output_format: str = "html",
    color_palette: str | list[str] | dict[str, str] | None = None,
) -> dict[str, Any]:
    """Generate an observed richness rarefaction curve.

    Args:
        alpha_rarefaction_path: Wide rarefaction TSV generated by the pipeline.
            The first column is interpreted as sequencing percentage/depth.
        metadata_path: Metadata TSV used to color samples by group. If it is
            missing, groups are inferred from sample IDs.
        output_dir: Directory for generated plots and tables.
        sample_id_col: Metadata column containing sample IDs.
        group_col: Metadata column containing group labels.
        output_format: `html`, `png`, `pdf`, `svg`, or `all`. Static formats require
            kaleido; HTML is always attempted.
        color_palette: Optional comma-separated colors or `Group:#hex` pairs.

    Returns:
        A dictionary describing generated files and skipped static exports.

    Raises:
        FileNotFoundError: If required input files are missing.
        ValueError: If required columns or metric values are invalid.
    """

    output_format = validate_output_format(output_format)
    resolved_output_dir = ensure_output_dir(output_dir)
    rarefaction = read_table(alpha_rarefaction_path, "alpha_rarefaction")
    first_column = rarefaction.columns[0]
    rarefaction = rarefaction.rename(columns={first_column: "Depth"}).copy()
    rarefaction["Depth"] = pd.to_numeric(rarefaction["Depth"], errors="raise")

    sample_columns = [column for column in rarefaction.columns if column != "Depth"]
    if not sample_columns:
        raise ValueError("alpha_rarefaction has no sample columns.")
    for column in sample_columns:
        rarefaction[column] = pd.to_numeric(rarefaction[column], errors="raise")

    long_table = rarefaction.melt(
        id_vars=["Depth"],
        value_vars=sample_columns,
        var_name="SampleID",
        value_name="Observed_OTUs",
    )
    sample_meta = build_sample_metadata(
        sample_columns,
        metadata_path=metadata_path,
        sample_id_col=sample_id_col,
        group_col=group_col,
    )
    long_table = long_table.merge(sample_meta, on="SampleID", how="left", validate="many_to_one")
    group_order = sort_groups(long_table["Group"].astype(str).tolist())
    color_map = resolve_color_palette(group_order, color_palette=color_palette)
    long_path = write_table(
        long_table,
        os.path.join(resolved_output_dir, "alpha_rarefaction_long.tsv"),
        include_index=False,
    )

    fig = px.line(
        long_table,
        x="Depth",
        y="Observed_OTUs",
        color="Group",
        line_group="SampleID",
        hover_data=["SampleID"],
        category_orders={"Group": group_order},
        color_discrete_map=color_map,
        title="Alpha Rarefaction Curve",
        labels={"Observed_OTUs": "Observed OTUs"},
        width=1050,
        height=650,
    )
    fig.update_traces(mode="lines", line_width=1.6)
    fig.update_layout(title_x=0.5, hovermode="x unified")
    apply_publication_theme(fig, width=1050, height=650)

    generated_files = [long_path]
    skipped_static: list[str] = []
    if output_format in {"html", "all"}:
        generated_files.append(
            write_html_figure(
                fig,
                os.path.join(resolved_output_dir, "alpha_rarefaction_curve.html"),
            )
        )
    write_optional_static(
        fig,
        os.path.join(resolved_output_dir, "alpha_rarefaction_curve"),
        output_format,
        width=1050,
        height=650,
        generated_files=generated_files,
        skipped_static=skipped_static,
    )
    generated_files.append(
        write_chart_index(
            resolved_output_dir,
            "Alpha Rarefaction Curve",
            generated_files,
            "Observed richness rarefaction curves colored by metadata group.",
        )
    )

    return {
        "alpha_rarefaction": os.path.abspath(alpha_rarefaction_path),
        "metadata": None if metadata_path is None else os.path.abspath(metadata_path),
        "output_dir": resolved_output_dir,
        "long_table": long_path,
        "plots": generated_files,
        "skipped_static_exports": skipped_static,
    }


TOOL_DEFINITIONS = [
    {
        "name": "plot_alpha_boxplots",
        "description": (
            "Generate alpha diversity boxplots from work/06_final/alpha/alpha_diversity.tsv. "
            "Outputs offline HTML files and a long-form TSV under work/06_final/plots by default."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "alpha_diversity_path": {"type": "string"},
                "metadata_path": {"type": "string"},
                "output_dir": {"type": "string", "default": DEFAULT_ALPHA_BOXPLOT_DIR},
                "metrics": {"type": "array", "items": {"type": "string"}},
                "sample_id_col": {"type": "string", "default": "SampleID"},
                "group_col": {"type": "string", "default": "Group"},
                "output_format": {
                    "type": "string",
                    "enum": ["html", "png", "pdf", "svg", "all"],
                    "default": "html",
                },
                "color_palette": {
                    "type": "string",
                    "description": "Optional comma-separated colors or Group:#hex pairs.",
                },
            },
        },
        "fn": plot_alpha_boxplots,
    },
    {
        "name": "plot_alpha_barplots",
        "description": (
            "Generate group mean alpha diversity barplots with standard deviation. "
            "Uses metadata grouping and writes results under work/06_final/plots by default."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "alpha_diversity_path": {"type": "string"},
                "metadata_path": {"type": "string"},
                "output_dir": {"type": "string", "default": DEFAULT_ALPHA_BARPLOT_DIR},
                "metrics": {"type": "array", "items": {"type": "string"}},
                "sample_id_col": {"type": "string", "default": "SampleID"},
                "group_col": {"type": "string", "default": "Group"},
                "output_format": {
                    "type": "string",
                    "enum": ["html", "png", "pdf", "svg", "all"],
                    "default": "html",
                },
                "color_palette": {
                    "type": "string",
                    "description": "Optional comma-separated colors or Group:#hex pairs.",
                },
            },
        },
        "fn": plot_alpha_barplots,
    },
    {
        "name": "plot_alpha_rarefaction_curve",
        "description": (
            "Generate an alpha rarefaction curve from work/06_final/alpha/alpha_rarefaction.tsv. "
            "Writes an offline HTML curve and long-form TSV under work/06_final/plots by default."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "alpha_rarefaction_path": {"type": "string"},
                "metadata_path": {"type": "string"},
                "output_dir": {"type": "string", "default": DEFAULT_ALPHA_RAREFACTION_DIR},
                "sample_id_col": {"type": "string", "default": "SampleID"},
                "group_col": {"type": "string", "default": "Group"},
                "output_format": {
                    "type": "string",
                    "enum": ["html", "png", "pdf", "svg", "all"],
                    "default": "html",
                },
                "color_palette": {
                    "type": "string",
                    "description": "Optional comma-separated colors or Group:#hex pairs.",
                },
            },
        },
        "fn": plot_alpha_rarefaction_curve,
    },
]
